# -*- coding: utf-8 -*-
"""week1_AISHANI_BILLORE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uSLYrlRmP57VWWcSz7RuyoOD9t9lQdrJ

# 📘 Week 1 Assignment — ML Foundations

**Topics Covered:** Python · NumPy · Pandas · Linear Algebra · Statistics · Probability Theory

---

> Complete all cells. Where marked `# YOUR CODE HERE`, write your solution. Do not change cell types or remove assertion blocks.
"""

# ── Setup ──────────────────────────────────────────────────────────────────
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import scipy.stats as stats
from io import StringIO

plt.rcParams['figure.figsize'] = (9, 4)
plt.rcParams['axes.spines.top'] = False
plt.rcParams['axes.spines.right'] = False
print('All imports OK ✓')

"""---
## Part 1 — Python Fundamentals

### 1.1 Data Types & Control Flow

Write a function `classify_number(n)` that:
- Returns `"negative"` if `n < 0`
- Returns `"zero"` if `n == 0`
- Returns `"small positive"` if `0 < n <= 10`
- Returns `"large positive"` otherwise
"""

def classify_number(n):
    #CODE
    if n < 0:
        return "negative"
    elif n == 0:
        return "zero"
    elif 0 < n <= 10:
        return "small positive"
    else:
        return "large positive"
    pass

# Tests
assert classify_number(-5) == "negative"
assert classify_number(0)  == "zero"
assert classify_number(7)  == "small positive"
assert classify_number(42) == "large positive"
print("1.1 passed ✓")

"""### 1.2 Data Structures

Given the list `words = ['apple', 'banana', 'cherry', 'apple', 'date', 'banana', 'apple']`:

1. Build a **dict** `word_count` mapping each word to its frequency using only a loop (no `Counter`).
2. Using a **set**, find all unique words and store in `unique_words`.
3. Using a **list comprehension**, build `long_words` containing words with more than 5 characters.
"""

words = ['apple', 'banana', 'cherry', 'apple', 'date', 'banana', 'apple']

# 1. word_count dict
word_count = {}
# CODE
for word in words:
    if word in word_count:
        word_count[word] += 1
    else:
        word_count[word] = 1

# 2. unique_words set
unique_words = None
#CODE
unique_words = set(words)
# 3. long_words list comprehension
long_words = None
#CODE
long_words= [word for word in words if len(word)>5]

# Tests
assert word_count == {'apple': 3, 'banana': 2, 'cherry': 1, 'date': 1}
assert unique_words == {'apple', 'banana', 'cherry', 'date'}
assert set(long_words) == {'banana', 'cherry'}
print("1.2 passed ✓")

"""### 1.3 Exceptions

Write `safe_divide(a, b)` that:
- Returns `a / b` normally
- Returns `None` if `b == 0` (catch `ZeroDivisionError`)
- Raises `TypeError` with message `"Inputs must be numeric"` if either input is not a number
"""

def safe_divide(a, b):
    #CODE
    try:
        return a / b
    except ZeroDivisionError:
        return None
    except TypeError:
        raise TypeError("Inputs must be numeric")
    pass

# Tests
assert safe_divide(10, 2) == 5.0
assert safe_divide(5, 0) is None
try:
    safe_divide('x', 2)
    assert False, "Should have raised TypeError"
except TypeError as e:
    assert str(e) == "Inputs must be numeric"
print("1.3 passed ✓")

"""### 1.4 Functions & Lambdas

1. Write a function `apply_twice(f, x)` that applies function `f` to `x` twice: `f(f(x))`.
2. Using a **lambda**, create `triple` that multiplies its input by 3.
3. Demonstrate: `apply_twice(triple, 4)` should return `36`.
"""

def apply_twice(f, x):
    #CODE
    return f(f(x))
    pass

triple = None
#CODE(lambda)
triple = lambda x: x * 3

result = apply_twice(triple, 4)
assert result == 36, f"Expected 36, got {result}"
print("1.4 passed ✓")

"""---
## Part 2 — NumPy

### 2.1 Array Creation & Shapes

1. Create a 1D array `arr1d` of integers 0–11.
2. Reshape it into a 2D array `arr2d` of shape `(3, 4)`.
3. Reshape `arr1d` into a 3D array `arr3d` of shape `(2, 2, 3)`.
4. Print the shape, ndim, and dtype of each.
"""

#CODE
arr1d = np.arange(12)
arr2d = arr1d.reshape(3, 4)
arr3d = arr1d.reshape(2, 2, 3)

# Tests
assert arr1d.shape == (12,)
assert arr2d.shape == (3, 4)
assert arr3d.shape == (2, 2, 3)
print("2.1 passed ✓")
print(f"arr2d:\n{arr2d}")
print(f"arr3d:\n{arr3d}")

"""### 2.2 Indexing & Slicing

Using `arr2d` from above:
1. Extract the **second row** → `row2`
2. Extract the **third column** → `col3`
3. Extract the **bottom-right 2×2 submatrix** → `sub`
4. Use **boolean indexing** to get all elements greater than 7 → `gt7`
"""

row2 = arr2d[1]  # CODE HERE
col3 = arr2d[:,2]  # CODE HERE
sub  = arr2d[1:,2:]  # CODE HERE
gt7  = arr2d[arr2d > 7] # CODE HERE

# Tests
assert list(row2) == [4, 5, 6, 7]
assert list(col3) == [2, 6, 10]
assert sub.shape == (2, 2)
assert list(gt7) == [8, 9, 10, 11]
print("2.2 passed ✓")

"""### 2.3 Operations & Dot Product

Given:
```
A = [[1, 2], [3, 4]]
B = [[5, 6], [7, 8]]
```

1. Compute **element-wise product** `C = A * B`
2. Compute **matrix multiplication** `D = A @ B`
3. Compute the **dot product** of vectors `[1,2,3]` and `[4,5,6]` → `dp`
4. Multiply all elements of `A` by scalar 3 → `E`
"""

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

C  = A * B # CODE HERE
D  = A @ B # CODE HERE
dp = np.dot([1,2,3],[4,5,6]) #  CODE HERE
E  = A * 3 # CODE HERE

# Tests
assert np.array_equal(C, [[5,12],[21,32]])
assert np.array_equal(D, [[19,22],[43,50]])
assert dp == 32
assert np.array_equal(E, [[3,6],[9,12]])
print("2.3 passed ✓")

"""---
## Part 3 — Pandas
"""

# Load dataset — do not modify this cell
CSV_DATA = """employee_id,name,department,salary,age,years_exp,performance
1,Alice,Engineering,95000,30,5,4.2
2,Bob,Marketing,72000,35,8,3.8
3,Carol,Engineering,88000,28,3,4.5
4,Dave,HR,61000,42,15,3.1
5,Eve,Engineering,102000,38,12,4.8
6,Frank,Marketing,68000,29,4,3.5
7,Grace,HR,,31,6,3.9
8,Hank,Engineering,91000,45,20,4.1
9,Iris,Marketing,75000,,7,4.0
10,Jack,Engineering,85000,33,8,
"""
df = pd.read_csv(StringIO(CSV_DATA))
print(f"Shape: {df.shape}")
df.head()

"""### 3.1 DataFrames vs Series

1. Extract the `salary` column as a **Series** → `salary_series`
2. Extract `name` and `department` columns as a **DataFrame** → `name_dept_df`
3. Print the type of each to confirm.
"""

salary_series = df['salary']  # CODE HERE
name_dept_df  = df[['name','department']] # CODE HERE

assert isinstance(salary_series, pd.Series)
assert isinstance(name_dept_df, pd.DataFrame)
print(f"salary_series type: {type(salary_series).__name__}")
print(f"name_dept_df type: {type(name_dept_df).__name__}")
print("3.1 passed ✓")

"""### 3.2 iloc & loc

1. Use `iloc` to select rows 2–4 (inclusive), columns 0–2 → `iloc_result`
2. Use `loc` to select rows where index is 5 or 6, columns `name` and `salary` → `loc_result`
"""

iloc_result = df.iloc[2:5,0:3]  # CODE HERE
loc_result  = df.loc[[5,6],['name','salary']]  #CODE HERE

assert iloc_result.shape == (3, 3)
assert list(loc_result.columns) == ['name', 'salary']
print("3.2 passed ✓")
display(iloc_result)
display(loc_result)

"""### 3.3 Filtering & Group By

1. Filter employees in **Engineering** with **salary > 90000** → `senior_eng`
2. Group by `department` and compute mean salary and mean performance → `dept_stats`
3. Sort `dept_stats` by mean salary descending.
"""

senior_eng = df[(df['department'] == 'Engineering') & (df['salary'] > 90000)] # CODE HERE
dept_stats = (
    df.groupby('department')[['salary', 'performance']]
    .mean()
    .sort_values(by='salary', ascending=False)
) # CODE HERE (groupby + agg + sort)

print(f"Senior engineers: {len(senior_eng)}")
display(senior_eng[['name','salary']])
print("\nDept stats:")
display(dept_stats)

"""### 3.4 Handling Missing Data

1. Identify which columns have missing values and how many → print a summary.
2. Fill missing `salary` with the **median salary** → `df_filled`
3. Fill missing `age` with the **mean age** (rounded to nearest int).
4. Drop rows where `performance` is missing.
5. Confirm no nulls remain.
"""

print("Missing values before:")
print(df.isnull().sum())

df_filled = df.copy()
# CODE HERE
df_filled['salary'].fillna(df['salary'].median(), inplace=True)
df_filled['age'].fillna(round(df['age'].mean()), inplace=True)
df_filled.dropna(subset=['performance'], inplace=True)

print("\nMissing values after:")
print(df_filled.isnull().sum())
assert df_filled.isnull().sum().sum() == 0, "Still has nulls!"
print("3.4 passed ✓")

"""---
## Part 4 — Linear Algebra

### 4.1 Vectors & Matrices as Data

1. Represent a 2D point `(3, 4)` as a NumPy vector and compute its **L2 norm** (Euclidean length).
2. Create a 3×3 matrix `M` (use any non-trivial values).
3. Plot the vector as an arrow from the origin using `matplotlib` — label axes and title it *"Vector Visualization"*.
"""

v = np.array([3, 4])
norm_v = np.linalg.norm(v)  # CODE HERE — use np.linalg.norm

M =np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])  #CODE HERE — any 3x3 matrix

# Plot
fig, ax = plt.subplots()
# CODE HERE — ax.quiver or ax.annotate to draw the vector arrow
ax.set_aspect('equal')
ax.set_xlim(-1, 5); ax.set_ylim(-1, 5)
ax.set_xlabel('x'); ax.set_ylabel('y')
ax.set_title('Vector Visualization')
ax.axhline(0, color='k', lw=0.8); ax.axvline(0, color='k', lw=0.8)
plt.tight_layout(); plt.show()

assert abs(norm_v - 5.0) < 1e-9
assert M.shape == (3, 3)
print(f"4.1 passed ✓  |v| = {norm_v}")

"""### 4.2 Matrix Operations in Practice

Let:
```
P = [[2, 1], [0, 3]]
Q = [[1, 4], [2, 0]]
```

1. Compute `P + Q` (matrix addition)
2. Compute `3 * P` (scalar multiplication)
3. Compute `P @ Q` (matrix multiplication)
4. Verify that matrix multiplication is **not commutative** — show `P @ Q ≠ Q @ P`.
"""

P = np.array([[2, 1], [0, 3]])
Q = np.array([[1, 4], [2, 0]])

PplusQ   = P + Q # CODE HERE
scalar3P = 3 * P # CODE HERE
PQ       = P @ Q  # CODE HERE
QP       = Q @ P  # CODE HERE

print(f"P + Q =\n{PplusQ}")
print(f"3*P =\n{scalar3P}")
print(f"P @ Q =\n{PQ}")
print(f"Q @ P =\n{QP}")
print(f"PQ == QP? {np.array_equal(PQ, QP)}")

assert not np.array_equal(PQ, QP), "They should differ!"
print("4.2 passed ✓")

"""### 4.3 Eigenvalues & Eigenvectors

For the matrix:
```
A = [[4, 1],
     [2, 3]]
```

1. Compute eigenvalues and eigenvectors using `np.linalg.eig`.
2. **Verify** the eigenvector equation: `A @ v = λ * v` for each eigenpair.
3. Plot both eigenvectors as arrows, scaled by their eigenvalues, on a 2D plot.
4. **Explain** in a markdown cell (below): what does it geometrically mean for a matrix to stretch a vector?
"""

A = np.array([[4, 1], [2, 3]], dtype=float)

eigenvalues, eigenvectors = np.linalg.eig(A) # CODE HERE

print(f"Eigenvalues: {eigenvalues}")
print(f"Eigenvectors (columns):\n{eigenvectors}")

# Verify Av = λv for each eigenpair
# CODE HERE
for i in range(len(eigenvalues)):
    v = eigenvectors[:, i]
    lhs = A @ v
    rhs = eigenvalues[i] * v
    print(np.allclose(lhs, rhs))

# Plot
# CODE HERE
plt.figure(figsize=(6,6))

origin = [0], [0]

for i in range(len(eigenvalues)):
    v = eigenvectors[:, i]

    plt.quiver(
        *origin,
        v[0],
        v[1],
        angles='xy',
        scale_units='xy',
        scale=1,
        label=f"Eigenvector {i+1}"
    )

plt.xlim(-1, 1)
plt.ylim(-1, 1)

plt.axhline(0)
plt.axvline(0)

plt.xlabel("X-axis")
plt.ylabel("Y-axis")
plt.title("Eigenvectors of Matrix A")

plt.legend()
plt.grid()

plt.show()

print("4.3 passed ✓")

"""**(4.3):Geometrically, a matrix changes the position of vectors by rotating, stretching, shrinking, or flipping them. Most vectors change direction after the transformation, but eigenvectors keep pointing in the same direction. They only become longer, shorter, or flipped. The eigenvalue tells how much the vector is stretched or squished.**

> *Replace this text with your explanation of what eigenvalues/eigenvectors mean geometrically — what does it mean for a matrix to "stretch" or "squish" a vector?*

### 4.4 SVD & Dimensionality Reduction

1. Create a random 4×3 matrix `X` (use `np.random.seed(42)`).
2. Compute its **SVD**: `U, S, Vt = np.linalg.svd(X, full_matrices=False)`.
3. **Reconstruct** `X` from the SVD and verify it matches the original.
4. Perform a **rank-1 approximation** using only the largest singular value/vector — call it `X_approx`.
5. Explain the relationship between SVD components and PCA in the markdown cell below.
"""

np.random.seed(42)
X = np.random.randn(4, 3)

U, S, Vt = np.linalg.svd(X, full_matrices=False) # CODE HERE

X_reconstructed = U @ np.diag(S) @ Vt # CODE HERE — reconstruct from U, S, Vt
X_approx        = S[0] * np.outer(U[:, 0], Vt[0, :]) # CODE HERE — rank-1 approximation

print(f"U shape: {U.shape}, S shape: {S.shape}, Vt shape: {Vt.shape}")
print(f"Singular values: {S}")
print(f"Reconstruction error: {np.linalg.norm(X - X_reconstructed):.2e}")
print(f"Rank-1 approximation:\n{X_approx}")

assert np.allclose(X, X_reconstructed, atol=1e-10), "Reconstruction failed!"
print("4.4 passed ✓")

"""**SVD** → PCA Connection(4.4):

In SVD, the matrix is divided into three parts: U, S, and Vt.

-U contains the important output directions after transformation.

-S contains singular values, which tell how important or strong each direction is. Larger values mean more important information.

-Vt contains the main directions in which the data spreads the most.
In PCA, these directions are called principal components. The matrix Vt contains the directions of maximum variance, so PCA mainly uses Vt to find the most important patterns in the data.

> *Explain: what are U, S, Vt in SVD, and how do they relate to principal components? Which matrix contains the directions of maximum variance?*

---
## Part 5 — Statistics

### 5.1 Descriptive vs Inferential Statistics

Using the cleaned `df_filled` from Part 3:

1. Compute **descriptive statistics** for the `salary` column: mean, median, std, min, max, IQR.
2. Plot a **histogram** of salary with a KDE overlay.
3. In the markdown cell below, write one sentence each defining: *population*, *sample*, *descriptive statistic*, *inferential statistic*.
"""

salary = df_filled['salary']

mean_s   = salary.mean() # CODE HERE
median_s = salary.median()  # CODE HERE
std_s    = salary.std()  # CODE HERE
min_s    = salary.min()  # CODE HERE
max_s    = salary.max()  # CODE HERE
iqr_s    = np.percentile(salary,75)-np.percentile(salary,25) # CODE HERE — use np.percentile

print(f"Mean:   {mean_s:.0f}")
print(f"Median: {median_s:.0f}")
print(f"Std:    {std_s:.0f}")
print(f"Range:  {min_s:.0f} – {max_s:.0f}")
print(f"IQR:    {iqr_s:.0f}")

# Histogram + KDE
fig, ax = plt.subplots()
# CODE HERE
salary.plot(kind='hist', bins=10, density=True, ax=ax)

salary.plot(kind='kde', ax=ax)

ax.set_xlabel('Salary'); ax.set_title('Salary Distribution')
plt.tight_layout(); plt.show()

"""**Definitions (5.1):**

- **Population: Population refers to the full set of people, items, or data that we want to examine in a study.**

**- Example: All customers visiting a mall in one month.**
- **Sample: A sample is a smaller group picked from the population to collect information in a simpler way.**

**- Example: 60 customers selected from the mall survey.**
- **Descriptive statistic: Descriptive statistics help in organizing and explaining data clearly with the help of averages, graphs, charts, and tables.**
- **Inferential statistic: Inferential statistics are used to study sample data and make assumptions or decisions about the larger population.**

### 5.2 Hypothesis Testing

**Scenario:** You suspect that Engineering salaries are significantly higher than the company average.

1. State the **null hypothesis H₀** and **alternative hypothesis H₁**.
2. Run a **one-sample t-test** comparing Engineering salaries against the overall mean salary.
3. Interpret the p-value at α = 0.05.
4. Also compute the **Pearson correlation** between `salary` and `years_exp`, and interpret it.
"""

eng_salaries = df_filled[df_filled['department'] == 'Engineering']['salary']
overall_mean = df_filled['salary'].mean()

# One-sample t-test
t_stat, p_value = stats.ttest_1samp(eng_salaries, overall_mean) # CODE HERE — use stats.ttest_1samp

print(f"Overall mean salary: {overall_mean:.0f}")
print(f"Engineering mean salary: {eng_salaries.mean():.0f}")
print(f"t-statistic: {t_stat:.4f}")
print(f"p-value: {p_value:.4f}")
print(f"Reject H0 at α=0.05? {p_value < 0.05}")

# Pearson correlation
#CODE HERE — use stats.pearsonr
r, r_pval = stats.pearsonr(
    df_filled['salary'],
    df_filled['years_exp']
)
print(f"\nPearson r (salary vs years_exp): {r:.4f}, p={r_pval:.4f}")

"""**H₀ / H₁ and Interpretation (5.2):**

- H₀: There is no significant difference between the engineering department’s average salary and the overall company average salary.
- H₁: The engineering department’s average salary is significantly different from the overall company average salary.
- Conclusion: Since the p-value (0.0280) is less than 0.05, we reject the null hypothesis. This means the engineering department salary is significantly different and higher than the overall average salary.

The Pearson correlation value r=0.0485 is very near to 0, which means salary and years of experience do not have a strong connection. Also, the p-value is greater than 0.05, so the relationship is not statistically significant. Therefore, in this dataset, years of experience does not affect salary much.

### 5.3 Error Metrics

Given these predictions and actuals, **implement from scratch** (no sklearn):
- MAE, MSE, RMSE
- R² Score
- Adjusted R² (assume 2 features)
"""

y_true = np.array([3.0, 5.0, 2.5, 7.0, 4.5, 6.0, 1.5, 8.0])
y_pred = np.array([2.8, 5.2, 2.1, 7.5, 4.0, 6.3, 2.0, 7.8])
n, p = len(y_true), 2

mae      = np.mean(np.abs(y_true - y_pred))  # CODE HERE
mse      = np.mean((y_true - y_pred) ** 2) # CODE HERE
rmse     = np.sqrt(mse)  # CODE HERE
r2       = 1 - (np.sum((y_true - y_pred) ** 2) / np.sum((y_true - np.mean(y_true)) ** 2))  # CODE HERE
adj_r2   = 1 - ((1 - r2) * (n - 1) / (n - p - 1))  # CODE HERE  formula: 1 - (1-r2)*(n-1)/(n-p-1)

print(f"MAE:        {mae:.4f}")
print(f"MSE:        {mse:.4f}")
print(f"RMSE:       {rmse:.4f}")
print(f"R²:         {r2:.4f}")
print(f"Adj. R²:    {adj_r2:.4f}")

"""### 5.4 Distribution Testing & Stationarity

1. Generate two samples: `s1` ~ Normal(0, 1), `s2` ~ Exponential(1), both n=200 (seed=0).
2. Run the **Kolmogorov-Smirnov test** (`stats.kstest`) comparing each against a standard normal CDF.
3. Generate a non-stationary time series (linear trend + noise). Run the **Augmented Dickey-Fuller test** (`adfuller` from `statsmodels`) and interpret the result.
4. Difference the series once and re-run ADF to confirm stationarity.
"""

from statsmodels.tsa.stattools import adfuller

np.random.seed(0)
s1 = np.random.normal(0, 1, 200)
s2 = np.random.exponential(1, 200)

# KS test — compare each against N(0,1)
ks_s1 = stats.kstest(s1, 'norm')  # CODE HERE
ks_s2 = stats.kstest(s2, 'norm')  # CODE HERE
print(f"KS test s1 (normal):      stat={ks_s1.statistic:.4f}, p={ks_s1.pvalue:.4f}")
print(f"KS test s2 (exponential): stat={ks_s2.statistic:.4f}, p={ks_s2.pvalue:.4f}")

# ADF test on non-stationary series
t = np.arange(200)
ts = 0.05 * t + np.random.normal(0, 1, 200)

adf_result = adfuller(ts)  # CODE HERE — adfuller(ts)
print(f"\nADF statistic: {adf_result[0]:.4f}")
print(f"ADF p-value:   {adf_result[1]:.4f}")
print(f"Stationary?    {adf_result[1] < 0.05}")

# Difference once and re-run
ts_diff = np.diff(ts)  #  CODE HERE — np.diff
adf_diff = adfuller(ts_diff)  # CODE HERE
print(f"\nAfter differencing — p-value: {adf_diff[1]:.4f}, Stationary? {adf_diff[1] < 0.05}")

"""### 5.5 Model Monitoring Concepts

1. Implement `compute_psi(expected, actual, bins=10)` that computes the **Population Stability Index** between two distributions.
2. Simulate a scenario where a model's input distribution shifts and plot both distributions.
3. In the markdown cell, define: *concept drift*, *covariate drift*, PSI thresholds (what values indicate no/minor/major shift), and one trigger for retraining.
"""

def compute_psi(expected, actual, bins=10):
    """
    PSI = sum((actual_pct - expected_pct) * ln(actual_pct / expected_pct))
    Add epsilon=1e-10 to avoid log(0).
    """
    # CODE HERE
    epsilon = 1e-10

    breakpoints = np.histogram_bin_edges(expected, bins=bins)

    expected_counts, _ = np.histogram(expected, bins=breakpoints)
    actual_counts, _ = np.histogram(actual, bins=breakpoints)

    expected_pct = expected_counts / len(expected) + epsilon
    actual_pct = actual_counts / len(actual) + epsilon

    psi = np.sum((actual_pct - expected_pct) * np.log(actual_pct / expected_pct))

    return psi
    pass

np.random.seed(1)
train_dist = np.random.normal(50, 10, 1000)    # training distribution
drift_dist = np.random.normal(65, 12, 1000)    # shifted production distribution

psi_value = compute_psi(train_dist, drift_dist)
print(f"PSI: {psi_value:.4f}")
print(f"Shift severity: {'Major' if psi_value > 0.2 else 'Minor' if psi_value > 0.1 else 'Stable'}")

# Plot both distributions
fig, ax = plt.subplots()
# CODE HERE
ax.hist(train_dist, bins=20, alpha=0.5, label='Training Distribution')

ax.hist(drift_dist, bins=20, alpha=0.5, label='Shifted Distribution')

ax.legend(); ax.set_title('Distribution Shift Visualization')
plt.tight_layout(); plt.show()

"""**Concept Drift vs Covariate Drift & PSI Thresholds (5.5):**

- **Concept drift: Concept drift means the model’s learning pattern changes with time because the connection between input data and output data is no longer the same. Due to this, prediction accuracy can decrease.**
- **Covariate drift: Covariate drift occurs when the nature or distribution of input data changes, even though the target/output relationship stays unchanged.**
- **PSI < 0.1: A PSI value below 0.1 shows that there is almost no change in the data distribution, so the model is performing normally and is considered stable.**
- **PSI 0.1–0.2:A PSI value between 0.1 and 0.2 indicates a moderate shift in data. The model may still work properly, but it should be continuously monitored.**
- **PSI > 0.2: A PSI value greater than 0.2 represents a large distribution change. This means the model may not perform well and retraining is recommended.**
- **Retraining trigger example: If the model accuracy starts dropping or the PSI value remains above 0.2 for a long period, new data should be used to retrain the model so that predictions remain accurate.**

---
## Part 6 — Probability Theory

### 6.1 Core Concepts

A bag contains: 4 red, 3 blue, 3 green marbles.

1. Define the sample space and compute P(red), P(blue), P(green).
2. Two marbles drawn **without replacement**. Compute:
   - P(first=red, second=blue) — **joint probability**
   - P(second=blue | first=red) — **conditional probability**
3. Are the two draws **independent**? Show mathematically.
"""

total = 10
red, blue, green = 4, 3, 3

p_red   = red/total  # CODE HERE
p_blue  = blue/total  # CODE HERE
p_green = green/total  # CODE HERE

# Joint: P(red first AND blue second)
p_red_then_blue = (4/10) * (3/9) # CODE HERE

# Conditional: P(blue second | red first)
p_blue_given_red = 3/9  # CODE HERE

# Independence check: are P(B|A) == P(B) ?
independent = (p_blue_given_red == p_blue)  #  CODE HERE — True/False

print(f"P(red)={p_red:.3f}, P(blue)={p_blue:.3f}, P(green)={p_green:.3f}")
print(f"P(red,blue): {p_red_then_blue:.4f}")
print(f"P(blue|red): {p_blue_given_red:.4f}")
print(f"P(blue):     {p_blue:.4f}")
print(f"Independent? {independent}")

"""### 6.2 Distributions in the Wild

1. **Normal**: Plot N(μ=0, σ=1) and N(μ=2, σ=0.5) PDFs on the same axes.
2. **Binomial**: A coin is flipped 20 times. Plot the PMF for k=0..20 with p=0.5 and p=0.7.
3. **Poisson**: Average 3 customers/minute. Plot the PMF for k=0..15.
4. For each, write one real-world ML use case in comments.
"""

fig, axes = plt.subplots(1, 3, figsize=(15, 4))

# ── Normal ──────────────────────────────────────────────────────────────────
x = np.linspace(-4, 6, 300)
# CODE HERE — plot two normal PDFs on axes[0]
axes[0].plot(x, stats.norm.pdf(x, 0, 1), label='μ=0, σ=1')
axes[0].plot(x, stats.norm.pdf(x, 2, 0.5), label='μ=2, σ=0.5')
axes[0].legend()
# ML use case: ...
#  Normal distribution is used in credit card fraud detection, where transactions that are very far from normal spending behavior are marked as suspicious.
axes[0].set_title('Normal Distribution')


# ── Binomial ────────────────────────────────────────────────────────────────
k = np.arange(0, 21)
# CODE HERE — plot PMFs for p=0.5 and p=0.7 on axes[1]
axes[1].plot(k, stats.binom.pmf(k, 20, 0.5), marker='o', label='p=0.5')
axes[1].plot(k, stats.binom.pmf(k, 20, 0.7), marker='o', label='p=0.7')
axes[1].legend()
# ML use case: ...
# Binomial distribution is used in medical testing systems where a test result can be positive or negative for a disease.
axes[1].set_title('Binomial Distribution')

# ── Poisson ─────────────────────────────────────────────────────────────────
k2 = np.arange(0, 16)
# CODE HERE — plot PMF (λ=3) on axes[2]
axes[2].plot(k2, stats.poisson.pmf(k2, 3), marker='o', label='λ=3')
axes[2].legend()
# ML use case: ...
# Poisson distribution is used in call centers to predict how many customer calls may arrive per minute or hour.
axes[2].set_title('Poisson Distribution')

plt.tight_layout(); plt.show()

"""### 6.3 Bayes' Theorem

**Scenario — Spam filter:**
- P(Spam) = 0.30 (prior)
- P("free" | Spam) = 0.80 (likelihood)
- P("free" | Not Spam) = 0.05

1. Compute P(Spam | "free") using Bayes' theorem.
2. Implement a simple `naive_bayes_predict(prior_spam, p_word_given_spam, p_word_given_ham)` that returns the posterior P(Spam | word).
3. In the markdown cell, map each term — **prior, likelihood, evidence, posterior** — to the spam example.
"""

p_spam            = 0.30
p_free_given_spam = 0.80
p_free_given_ham  = 0.05
p_ham             = 1 - p_spam

# P(free) — law of total probability
p_free = (p_free_given_spam * p_spam) + (p_free_given_ham * p_ham)  #  CODE HERE

# Bayes
p_spam_given_free = (p_free_given_spam * p_spam) / p_free  # CODE HERE

print(f"P('free'): {p_free:.4f}")
print(f"P(Spam | 'free'): {p_spam_given_free:.4f}")

def naive_bayes_predict(prior_spam, p_word_given_spam, p_word_given_ham):
    # CODE HERE
    p_ham = 1 - prior_spam

    p_word = (p_word_given_spam * prior_spam) + (p_word_given_ham * p_ham)

    posterior = (p_word_given_spam * prior_spam) / p_word

    return posterior
    pass

pred = naive_bayes_predict(0.30, 0.80, 0.05)
assert abs(pred - p_spam_given_free) < 1e-9
print(f"naive_bayes_predict: {pred:.4f}")
print("6.3 passed ✓")

"""**Bayes Term Mapping (6.3):**

| Term | Formula | In this example |
|------|---------|-----------------|
| Prior | P(Spam) |  Probability that an email is spam before checking the word "free" |
| Likelihood | P(word \| Spam) | Probability of seeing the word "free" in a spam email |
| Evidence | P(word) | Total probability of the word "free" appearing in any email |
| Posterior | P(Spam \| word) | Probability that the email is spam after seeing the word "free" |

### 6.4 Central Limit Theorem

1. Define a population following an **exponential distribution** (λ=1, size=100,000).
2. Repeatedly draw samples of size `n=30` and record their means — do this 5,000 times.
3. Plot the histogram of sample means.
4. Overlay the **theoretical normal distribution** predicted by the CLT: μ = population mean, σ = population_std / sqrt(n).
5. Run a KS test to confirm the distribution of sample means is approximately normal.
"""

np.random.seed(7)
population = np.random.exponential(scale=1.0, size=100_000)

n_samples = 5000
sample_size = 30
sample_means = np.array([
    np.random.choice(population, sample_size).mean()
    for _ in range(n_samples)
])  # CODE HERE — array of 5000 sample means

pop_mean = population.mean()
pop_std  = population.std()
clt_std  = pop_std / np.sqrt(sample_size)  # CODE HERE — predicted std of sample means

print(f"Population mean: {pop_mean:.4f}, Population std: {pop_std:.4f}")
print(f"Sample means mean: {sample_means.mean():.4f}, std: {sample_means.std():.4f}")
print(f"CLT predicted std: {clt_std:.4f}")

# Plot
fig, ax = plt.subplots()
# CODE HERE — histogram of sample means + theoretical normal overlay
ax.hist(sample_means, bins=30, density=True, alpha=0.6, label='Sample Means')

x = np.linspace(sample_means.min(), sample_means.max(), 200)

ax.plot(x, stats.norm.pdf(x, pop_mean, clt_std),
        label='Theoretical Normal')

ax.legend()
ax.set_title('CLT: Distribution of Sample Means')
plt.tight_layout(); plt.show()

# KS test
ks_result = stats.kstest(sample_means, 'norm', args=(pop_mean, clt_std))
print(f"KS test p-value: {ks_result.pvalue:.4f} → Approximately normal? {ks_result.pvalue > 0.05}")

"""**CLT Reflection (6.4): The Central Limit Theorem is important because it tells us that when we take many samples, the average of those samples follows a normal distribution, even if the original data is not normal. This makes data analysis easier and more reliable in statistics and machine learning.**

**CLT supports the normality assumption used in many statistical methods like hypothesis testing, confidence intervals, and regression models.**

> *In 2–3 sentences: Why does this result matter for statistics and machine learning? What assumption does the CLT justify in many classical statistical tests?*

---
## 🏁 Submission Checklist

Before submitting, verify:

- [✓] All `assert` blocks pass without errors
- [✓] All `# YOUR CODE HERE` cells are filled
- [✓] All markdown reflection cells are filled in your own words
- [✓] All plots render with labels and titles
- [✓] Notebook runs cleanly from top to bottom (`Kernel → Restart & Run All`)

**Save as:** `week1_<your_name>.ipynb`
"""

